
cd C:\Users\97254\Documents\MyProjects\PyCv\pycv\_lib\core

printf("offsets is %" NPY_INTP_FMT "\n", (footprint).offsets[jj]);
printf("value is %.2f", value);
NPY_LONGDOUBLE_FMT
printf("[");
for (ii = 0; ii < sz; ii++) {
    printf("%" NPY_INTP_FMT ", ", footprint[ii]);
}
printf("]\n");

printf("[%" NPY_INTP_FMT ", %" NPY_INTP_FMT "]\n", circles_run[0], circles_run[1]);


python c_pycv_setup.py install
py -m pip uninstall C_PyCv

python c_pycv_setup.py build_ext
python c_pycv_setup.py develop




# coins = load_image('coins.png')[88:]
# coins_med = median_filter(coins, (5, 5))
# coins_bin, th = im_threshold(coins_med, 'otsu')